/**
 * APPLICATION / DOMAIN TYPES
 *
 * These types are NOT generated by `supabase gen types`. They are hand-maintained
 * domain types, helper string-literal enums, and composite public shapes used by
 * React components, services, and mappers. Keep this file separate from the
 * generated database types so that future `npm run db:types` runs never erase
 * custom domain definitions.
 */

import type { Theme } from '@/lib/types/theme';

export type { Theme };

export type BookingStatus =
  | 'pending'
  | 'awaiting_payment'
  | 'confirmed'
  | 'cancelled'
  | 'expired'
  | 'refunded'
  | 'partially_refunded';

export type BookingMode = 'scheduled' | 'enquiry' | 'external';

export type BookingSource = 'website' | 'admin' | 'wix_import';

export type ContentStatus = 'draft' | 'published' | 'archived';

export type ParticipantType = 'adult' | 'child' | 'unspecified';

export type PaymentStatus =
  | 'created'
  | 'pending'
  | 'paid'
  | 'failed'
  | 'cancelled'
  | 'partially_refunded'
  | 'refunded';

export type SessionStatus =
  'draft' | 'scheduled' | 'sold_out' | 'cancelled' | 'completed';

export type MediaSource = 'upload' | 'wix_import' | 'generated';

export type MediaRole = 'featured' | 'gallery' | 'detail';

export type SubscriberStatus = 'subscribed' | 'unsubscribed' | 'suppressed';

export type AdminRole = 'owner' | 'manager' | 'editor';

export type WorkshopCategory = {
  id: string;
  name: string;
  slug: string;
  description: string | null;
  suggestedTheme: Theme;
  displayOrder: number;
  isVisible: boolean;
};

export type Instructor = {
  id: string;
  displayName: string;
  slug: string;
  biography: string | null;
  profileMediaId: string | null;
  isActive: boolean;
  displayOrder: number;
};

export type MediaAsset = {
  id: string;
  originalFilename: string;
  storageBucket: string;
  storagePath: string;
  mimeType: string;
  width: number | null;
  height: number | null;
  fileSizeBytes: number | null;
  altText: string;
  caption: string | null;
  source: MediaSource;
  wixUrl: string | null;
  checksum: string | null;
  archivedAt: string | null;
};

export type Workshop = {
  id: string;
  categoryId: string;
  title: string;
  slug: string;
  shortDescription: string | null;
  description: string | null;
  practicalInformation: string | null;
  minimumAge: number | null;
  maximumAge: number | null;
  defaultDurationMinutes: number;
  defaultCapacity: number;
  defaultPriceGrossGrosz: number;
  currency: string;
  suggestedTheme: Theme | null;
  featuredMediaId: string | null;
  bookingMode: BookingMode;
  externalBookingUrl: string | null;
  status: ContentStatus;
  isFeatured: boolean;
  seoTitle: string | null;
  seoDescription: string | null;
  archivedAt: string | null;
};

export type WorkshopSession = {
  id: string;
  workshopId: string;
  instructorId: string | null;
  startsAt: string;
  endsAt: string;
  timezone: string;
  capacity: number;
  reservedCount: number;
  priceGrossGrosz: number;
  currency: string;
  locationName: string | null;
  locationAddress: string | null;
  /** Normalized venue: suchy-las | ptasie-radio | other | null */
  venueKey: string | null;
  status: SessionStatus;
  bookingOpensAt: string | null;
  bookingClosesAt: string | null;
  externalBookingUrl: string | null;
};

export type ContentPage = {
  id: string;
  title: string;
  slug: string;
  excerpt: string | null;
  content: string | null;
  status: ContentStatus;
  suggestedTheme: Theme | null;
  seoTitle: string | null;
  seoDescription: string | null;
  publishedAt: string | null;
  archivedAt: string | null;
  updatedAt: string;
};

export type BlogPost = {
  id: string;
  title: string;
  slug: string;
  excerpt: string;
  content: string;
  featuredMediaId: string | null;
  status: ContentStatus;
  authorName: string | null;
  publishedAt: string | null;
  seoTitle: string | null;
  seoDescription: string | null;
  legacyWixUrl: string | null;
  archivedAt: string | null;
  updatedAt: string;
};

export type GalleryItem = {
  id: string;
  mediaAssetId: string;
  title: string | null;
  description: string | null;
  category: string | null;
  displayOrder: number;
  isVisible: boolean;
  updatedAt: string;
};

export type LegacyRedirect = {
  id: string;
  sourcePath: string;
  destinationPath: string;
  statusCode: 301 | 308;
  notes: string | null;
};

export type SiteSetting = {
  key: string;
  value: unknown;
  description: string | null;
};

export type AdminUser = {
  userId: string;
  role: AdminRole;
  displayName: string;
  isActive: boolean;
  createdAt: string;
  updatedAt: string;
  lastLoginAt: string | null;
};

export type AdminAuditLog = {
  id: string;
  actorUserId: string;
  actorRole: AdminRole;
  action: string;
  entityType: string;
  entityId: string | null;
  summary: string;
  changedFields: unknown;
  requestMetadata: unknown;
  createdAt: string;
};

export type WorkshopWithCategory = Workshop & {
  category: WorkshopCategory | null;
};

export type WorkshopWithSessions = WorkshopWithCategory & {
  sessions: WorkshopSession[];
  instructors: Instructor[];
  media: MediaAsset[];
};

export type PublicSiteSettings = {
  studioName: string;
  studioAddress: string;
  studioEmail: string;
  studioPhone: string;
  bookingCtaLabel: string;
  defaultSeoTitle: string;
  defaultSeoDescription: string;
};
