/* Auto-generated from reference/original-site — do not invent content. */
export const archiveBlogPosts = {
  indexOrder: [
    'letnia-akademia-artystyczna-całe-wakacje',
    'dlaczego-warto-wybrać-naszą-pracownię-ceramiki-dla-twoich-kreatywnych-potrzeb',
    'startujemy-z-zapisamy-na-wrzesień-bogata-oferta-warsztatów-dla-dzieci-rysunek-malarstwo-ceramika',
    'czym-zajmuje-się-pracownia-ceramiki-nero',
    'pikniki-artystyczne-na-polanie-przed-pracownią-ceramiki-nero',
    'czy-wiecie-że-prowadzimy-również-warsztaty-rysunku-malarstwa-i-ceramiki',
    'nowe-warsztaty-ceramika-dla-smyka-od-stycznia-2025',
    'nowe-warsztaty-ceramika-dla-smyka',
    'bycie-w-procesie-podczas-warsztatów-z-ceramiki',
    'glina-do-wina',
    'dziękujemy-wszystkim-którzy-są-z-nami',
    'wspaniała-historia-pracowni-od-miłości-do-gotowania-do-tworzenia-inspirującej-wspólnoty',
    'jak-zacząć-przygodę-z-ceramiką',
  ],
  posts: [
    {
      slug: 'bycie-w-procesie-podczas-warsztatów-z-ceramiki',
      route: '/post/bycie-w-procesie-podczas-warsztatów-z-ceramiki',
      title: 'Bycie w procesie podczas warsztatów z ceramiki',
      author: 'Gosia Nero',
      date: '22 kwi 2024',
      readingTime: '2 minut(y) czytania',
      paragraphs: [
        'Bycie w Procesie: Tworzenie z Gliny',
        'Lepienie z gliny to sztuka, która ma w sobie coś magicznego. Proces tworzenia zaczyna się od zwykłego kawałka gliny, który stopniowo nabiera kształtu i formy pod naszymi palcami. Bycie w procesie lepienia z gliny to podróż pełna odkryć, wyzwań i satysfakcji.',
        'Pierwszym krokiem w lepieniu z gliny jest przygotowanie materiału. Glina jest formowalna i plastyczna, co sprawia, że idealnie nadaje się do tworzenia różnorodnych przedmiotów, od naczyń po rzeźby. Po wybraniu odpowiedniej kawałka gliny, następuje moment, w którym twórca łączy się z materiałem. To początek interakcji między człowiekiem a gliną, gdzie obie strony wpływają na siebie nawzajem.',
        'Kolejnym etapem jest formowanie gliny. Palce delikatnie modelują materiał, nadając mu życie i charakter. Każdy ruch, każde uderzenie palcami pozostawia ślad, który wpływa na ostateczny kształt dzieła. To momenty pełne koncentracji i skupienia, gdzie czas zatrzymuje się, a twórca staje się jednością z tworzonym obiektem.',
        'Podczas pracy z gliną często napotykamy na wyzwania. Nie zawsze materiał zachowuje się tak, jakbyśmy tego chcieli, czasem nie udaje się osiągnąć pożądanego efektu za pierwszym razem. Jednak to właśnie w tych momentach uczymy się cierpliwości, wytrwałości i elastyczności. Każdy błąd staje się lekcją, która prowadzi nas dalej w procesie tworzenia.',
        'Jednak nie tylko trudności są częścią procesu lepienia z gliny. Każdy kawałek gliny, który nabiera kształtu pod naszymi palcami, to moment triumfu. To uczucie, gdy patrzymy na stworzone dzieło i widzimy w nim odzwierciedlenie naszej wyobraźni i pracy. To także radość płynąca z możliwości wyrażenia siebie poprzez sztukę.',
        'Kiedy nasze dzieło jest gotowe, następuje moment wypalania. To proces, który nadaje glinie trwałość i wytrzymałość. Wypalanie to jakby ostatnia pieczęć na naszej pracy, która czyni ją trwałą i niezmienną.',
        'Lepienie z gliny to nie tylko tworzenie przedmiotów, ale również podróż w głąb siebie. To proces, który uczy nas pokory wobec materii, skupienia i wewnętrznej siły. Bycie w procesie lepienia z gliny to nie tylko działanie fizyczne, to także podróż emocjonalna i duchowa.',
        '13 wyświetleń',
      ],
      images: [
        {
          alt: '(no alt)',
          src: '/images/wix-migrated/747d6f_ff24ad7d7859452782d34e7ac82d8133.jpg',
          dims: '938x350',
        },
        {
          alt: '(no alt)',
          src: '/images/wix-migrated/747d6f_834716a3d7184a77b4462bb715a0d9bf.jpg',
          dims: '740x983',
        },
        {
          alt: 'Letnia akademia artystyczna całe wakacje',
          src: '/images/wix-migrated/747d6f_db20092f210148bdb5f759fb972dcbe1.jpg',
          dims: '289x162',
        },
        {
          alt: 'Dlaczego Warto Wybrać Naszą Pracownię Ceramiki dla Twoich Kreatywnych Potrzeb?',
          src: '/images/wix-migrated/747d6f_0a4d8816a90344e9a161a8f1af115f5f.png',
          dims: '289x162',
        },
      ],
      categoryHints: [],
    },
    {
      slug: 'czy-wiecie-że-prowadzimy-również-warsztaty-rysunku-malarstwa-i-ceramiki',
      route:
        '/post/czy-wiecie-że-prowadzimy-również-warsztaty-rysunku-malarstwa-i-ceramiki',
      title:
        'Czy wiecie, że prowadzimy również warsztaty rysunku, malarstwa i ceramiki ?',
      author: 'Gosia Nero',
      date: '19 maj 2025',
      readingTime: '1 minut(y) czytania',
      paragraphs: [
        'Czy wiecie, że w naszej pracowni prowadzimy również warsztaty z rysunku, malarstwa i ceramiki? 🎨🖌️🧱',
        'Z ogromną radością informujemy, że od września ruszają nowe, stałe grupy zajęciowe dla dzieci i dorosłych!',
        'Nasza pracownia to nie tylko miejsce, w którym powstają ceramiczne dzieła – to także przestrzeń pełna twórczej energii, inspiracji i artystycznych spotkań. Zapraszamy wszystkich, którzy chcą rozwijać swoje pasje, nauczyć się czegoś nowego lub po prostu spędzić czas w kreatywny sposób.',
        '👧🧑 Dla dzieci (w wieku 7–10 oraz 11–15 lat) przygotowaliśmy zajęcia łączące naukę technik rysunku, malarstwa i ceramiki. Pracujemy z ołówkiem, kredkami, akwarelą, gliną – tworzymy, eksperymentujemy i świetnie się bawimy!',
        '👩‍🎨🧑‍🎨 Dorośli i młodzież mogą liczyć na pogłębioną pracę twórczą – niezależnie od poziomu zaawansowania. Zajęcia to doskonała okazja, by oderwać się od codzienności i dać się ponieść artystycznej pasji.',
        '📅 Zajęcia ruszają we wrześniu, a liczba miejsc jest ograniczona – zachęcamy do wcześniejszych zapisów!',
        'Więcej informacji o terminach, grupach i zapisach znajdziesz w zakładce Zapisy.',
        'Masz pytania? Napisz do nas – z przyjemnością odpowiemy.',
        'Do zobaczenia w pracowni! ✨Zespół Pracowni Ceramiki NERO',
        '6 wyświetleń',
      ],
      images: [
        {
          alt: '(no alt)',
          src: '/images/wix-migrated/747d6f_da600fb92cac4d629b7833190b681fa2.jpg',
          dims: '740x830',
        },
        {
          alt: 'Letnia akademia artystyczna całe wakacje',
          src: '/images/wix-migrated/747d6f_db20092f210148bdb5f759fb972dcbe1.jpg',
          dims: '289x162',
        },
        {
          alt: 'Dlaczego Warto Wybrać Naszą Pracownię Ceramiki dla Twoich Kreatywnych Potrzeb?',
          src: '/images/wix-migrated/747d6f_0a4d8816a90344e9a161a8f1af115f5f.png',
          dims: '289x162',
        },
      ],
      categoryHints: [],
    },
    {
      slug: 'czym-zajmuje-się-pracownia-ceramiki-nero',
      route: '/post/czym-zajmuje-się-pracownia-ceramiki-nero',
      title: 'Czym zajmuje się Pracownia Ceramiki NERO?',
      author: 'Gosia Nero',
      date: '8 cze 2025',
      readingTime: '1 minut(y) czytania',
      paragraphs: [
        'Pracownia Ceramiki NERO to przestrzeń twórcza, w której glina spotyka się z wyobraźnią, a rękodzieło z pasją i spokojem. Nasza pracownia powstała z potrzeby tworzenia, dzielenia się pięknem rzemiosła i budowania wspólnoty wokół sztuki użytkowej i artystycznej.',
        '💡 Co robimy na co dzień?',
        'W naszej pracowni prowadzimy różnorodne warsztaty ceramiczne – zarówno dla dzieci, jak i dorosłych, początkujących i bardziej zaawansowanych. Uczymy od podstaw, ale też wspieramy w rozwoju indywidualnych projektów. Praca z gliną daje możliwość wyciszenia, skupienia i radości z tworzenia – to idealna forma odpoczynku od codziennego pędu.',
        'Organizujemy:',
        'Zajęcia cykliczne – regularne kursy ceramiki w małych grupach',
        'Warsztaty jednorazowe – m.in. nasze popularne „Glina do wina”',
        'Półkolonie artystyczne dla dzieci – pełne kreatywnych aktywności',
        'Zajęcia rodzinne i indywidualne – idealne na prezent lub wspólny czas',
        'Wieczory panieńskie, urodziny i eventy firmowe – z ceramiką w roli głównej',
        '🎨 Co tworzymy?',
        'Uczymy lepienia ręcznego, modelowania, tworzenia naczyń i form użytkowych oraz dekoracyjnych. Pracujemy z różnymi technikami szkliwienia i zdobienia ceramiki. Każdy uczestnik naszych zajęć tworzy coś własnego i niepowtarzalnego – naczynia, misy, kubki, figurki, rzeźby.',
        '🏡 Gdzie nas znaleźć?',
        'Nasza pracownia mieści się w Suchym Lesie, przy ul. Podgórnej 3 – zaledwie kilka minut od Poznania. To kameralne, ciepłe miejsce stworzone do twórczego działania, odpoczynku i spotkań.',
        'Jeśli szukasz przestrzeni, w której możesz poczuć glinę pod palcami, stworzyć coś pięknego i poczuć dumę z własnej pracy – serdecznie zapraszamy do Pracowni Ceramiki NERO.',
        'Zajrzyj do nas – być może ceramika stanie się Twoją nową pasją 💛',
        'Pracownia ceramiki Nero Suchy Las pod Poznaniem',
        '16 wyświetleń',
      ],
      images: [
        {
          alt: '(no alt)',
          src: '/images/wix-migrated/747d6f_4e60c15e658a4b79a0195819e842eb93.jpg',
          dims: '243x243',
        },
        {
          alt: '(no alt)',
          src: '/images/wix-migrated/747d6f_8af7f884525642d8b67fe0bf709a577b.png',
          dims: '244x243',
        },
        {
          alt: '(no alt)',
          src: '/images/wix-migrated/747d6f_da600fb92cac4d629b7833190b681fa2.jpg',
          dims: '243x243',
        },
        {
          alt: '(no alt)',
          src: '/images/wix-migrated/747d6f_75f475196e3244da9e18720cc382ba9b.jpg',
          dims: '243x243',
        },
        {
          alt: '(no alt)',
          src: '/images/wix-migrated/747d6f_c4f1c7aee49e46c295f3910e257e8f69.jpg',
          dims: '244x243',
        },
        {
          alt: '(no alt)',
          src: '/images/wix-migrated/747d6f_47a6a2b4713241168b37ff242c99303e.jpg',
          dims: '243x243',
        },
        {
          alt: 'Pracownia ceramiki Nero Suchy Las pod Poznaniem',
          src: '/images/wix-migrated/747d6f_bf6fc0998d4a4467945a89a8340eb7cd.png',
          dims: '740x424',
        },
        {
          alt: 'Letnia akademia artystyczna całe wakacje',
          src: '/images/wix-migrated/747d6f_db20092f210148bdb5f759fb972dcbe1.jpg',
          dims: '289x162',
        },
        {
          alt: 'Dlaczego Warto Wybrać Naszą Pracownię Ceramiki dla Twoich Kreatywnych Potrzeb?',
          src: '/images/wix-migrated/747d6f_0a4d8816a90344e9a161a8f1af115f5f.png',
          dims: '289x162',
        },
      ],
      categoryHints: [],
    },
    {
      slug: 'dlaczego-warto-wybrać-naszą-pracownię-ceramiki-dla-twoich-kreatywnych-potrzeb',
      route:
        '/post/dlaczego-warto-wybrać-naszą-pracownię-ceramiki-dla-twoich-kreatywnych-potrzeb',
      title:
        'Dlaczego Warto Wybrać Naszą Pracownię Ceramiki dla Twoich Kreatywnych Potrzeb?',
      author: 'Gosia Nero',
      date: null,
      readingTime: '2 minut(y) czytania',
      paragraphs: [
        '10 lip',
        'Tworzenie ceramiki to nie tylko rzemiosło, ale także sposób na wyrażenie siebie i rozwijanie kreatywności. Wybór odpowiedniej pracowni ceramiki może znacząco wpłynąć na Twoje doświadczenia i efekty pracy. Nasza pracownia wyróżnia się na tle innych miejsc, oferując unikalne podejście, wsparcie i atmosferę, które pomagają każdemu twórcy rozwinąć skrzydła. W tym wpisie wyjaśniamy, dlaczego warto postawić właśnie na naszą pracownię.',
        'Ręcznie formowana ceramiczna miska na kole garncarskim',
        'Indywidualne podejście do każdego twórcy',
        'W naszej pracowni każdy uczestnik traktowany jest indywidualnie. Niezależnie od poziomu zaawansowania, oferujemy wsparcie dostosowane do Twoich potrzeb. Początkujący mogą liczyć na cierpliwe wprowadzenie w techniki ceramiki, a doświadczeni artyści znajdą u nas przestrzeń do eksperymentów i rozwijania własnego stylu.',
        'Konsultacje i porady – nasi instruktorzy pomagają rozwiązać problemy techniczne i artystyczne.',
        'Dopasowane materiały – dobieramy glinę i narzędzia odpowiednie do Twoich projektów.',
        'Elastyczne godziny pracy – nie narzucamy tobie co tworzysz podczas zajęć Ceramika dla dorosłych lub Glina do wina -tworzysz projekty, które pasują do Ciebie do twojego wnętrza.',
        'Profesjonalne wyposażenie i materiały',
        'Nasza pracownia dysponuje nowoczesnym sprzętem, który ułatwia tworzenie ceramiki na różnych etapach. Posiadamy w pełni wyposażoną salę, piec do wypału oraz szeroki wybór farb i szkliw. Dzięki temu możesz realizować zarówno proste formy, jak i skomplikowane projekty.',
        'Dzięki temu masz pewność, że Twoje prace będą trwałe i estetyczne.',
        'Przyjazna i inspirująca atmosfera',
        'Tworzenie ceramiki wymaga skupienia, ale także inspiracji. Nasza pracownia to miejsce, gdzie panuje ciepła i wspierająca atmosfera. Spotkasz tu ludzi z pasją, którzy chętnie dzielą się doświadczeniem i pomysłami. Organizujemy także warsztaty tematyczne i spotkania, które pomagają rozwijać umiejętności i nawiązywać nowe znajomości.',
        'Regularne warsztaty z różnych technik ceramicznych, malowania i rysowania',
        'Spotkania artystyczne i wymiana doświadczeń',
        'Przyjazne otoczenie sprzyjające kreatywności',
        'Przestronna pracownia ceramiki z półkami pełnymi wyrobów ceramicznych',
        'Możliwość realizacji indywidualnych projektów i zamówień',
        'Tworzysz to co czujesz. Pomagamy klientom przygotować unikalne prezenty, dekoracje do domu czy elementy wyposażenia wnętrz. Dzięki temu Twoje prace mogą stać się nie tylko hobby, ale także częścią Twojego domu.',
        'Tworzenie spersonalizowanych zestawów ceramicznych',
        'Wsparcie w przygotowaniu projektów',
        'Możliwość zakupu ceramiki i rękodzieła w naszym lokalnym sklepie',
        'Rozwój umiejętności i pasji',
        'Nasza pracownia to miejsce, gdzie możesz stale rozwijać swoje umiejętności. Oferujemy kursy i szkolenia prowadzone przez doświadczonych ceramików, które pozwalają poznać nowe techniki i doskonalić warsztat. To także doskonała okazja, by odkryć nowe obszary twórczości i znaleźć własny styl.',
        'Kursy podstawowe i zaawansowane',
        'Warsztaty specjalistyczne, rysunek, malarstwo , ceramika',
        'Możliwość uczestnictwa w wystawach i konkursach organizowanych przez pracownię',
        'Podsumowanie',
        'Wybór naszej pracowni ceramiki to inwestycja w rozwój Twojej kreatywności i umiejętności. Oferujemy indywidualne podejście, profesjonalne wyposażenie, inspirującą atmosferę oraz wsparcie na każdym etapie tworzenia. Niezależnie od tego, czy dopiero zaczynasz swoją przygodę z ceramiką, czy jesteś doświadczonym artystą, znajdziesz u nas miejsce, które pomoże Ci realizować Twoje pomysły i pasje.',
        'Zapraszamy do odwiedzenia naszej pracowni i przekonania się, jak wiele możesz zyskać, wybierając właśnie nas. Twoja kreatywność zasługuje na najlepsze warunki do rozwoju.',
        '4 wyświetlenia',
      ],
      images: [
        {
          alt: 'Widok z bliska na ręcznie formowaną ceramiczną miskę na kole garncarskim',
          src: '/images/wix-migrated/747d6f_e5ad882b2465483ebd9497dece123b1c.jpeg',
          dims: '740x987',
        },
        {
          alt: 'Widok z poziomu oczu na przestronną pracownię ceramiki z półkami pełnymi wyrobów ceramicznych',
          src: '/images/wix-migrated/747d6f_79268ec496de49ba985b6980ba3528c4.jpeg',
          dims: '740x987',
        },
        {
          alt: 'Letnia akademia artystyczna całe wakacje',
          src: '/images/wix-migrated/747d6f_db20092f210148bdb5f759fb972dcbe1.jpg',
          dims: '289x162',
        },
        {
          alt: 'Czym zajmuje się Pracownia Ceramiki NERO?',
          src: '/images/wix-migrated/747d6f_bf6fc0998d4a4467945a89a8340eb7cd.png',
          dims: '289x162',
        },
      ],
      categoryHints: [],
    },
    {
      slug: 'dziękujemy-wszystkim-którzy-są-z-nami',
      route: '/post/dziękujemy-wszystkim-którzy-są-z-nami',
      title: 'Dziękujemy wszystkim, którzy są z nami!',
      author: 'Gosia Nero',
      date: '17 lut 2024',
      readingTime: '1 minut(y) czytania',
      paragraphs: [
        'Drodzy Przyjaciele Ceramiki Nero,',
        'Chciałbym z całego serca wyrazić ogromną wdzięczność za waszą nieustanną obecność i wsparcie. To dzięki Wam pracownia ceramiki Nero staje się miejscem pełnym kreatywności, pasji i wyjątkowych chwil.',
        'Dziękujemy za każde serduszko, za każdy like, który motywuje nas do tworzenia jeszcze piękniejszych dzieł. Wasza wirtualna obecność dodaje nam skrzydeł i energii do działania. To niezmiernie ważne dla naszego zespołu i dla rozwoju pracowni.',
        'Jesteśmy wdzięczni również za liczne warsztaty, na które tak chętnie przychodzicie. Wasza ciekawość, zaangażowanie i radość podczas spotkań sprawiają, że każda lekcja ceramiki to nie tylko nauka, ale również wspólne tworzenie niepowtarzalnych dzieł sztuki.',
        'Dziękujemy za zaufanie, które nam okazujecie, przysyłając swoje dzieci na warsztaty. To dla nas wielki zaszczyt móc wprowadzić najmłodszych w świat ceramiki i rozwijać w nich pasję do sztuki.',
        'Niech nasza wspólna przygoda trwa dalej! Już niedługo czekają nas kolejne emocjonujące wydarzenia poza pracownią. Z okazji nadchodzącego Dnia Kobiet obiecujemy wiele niespodzianek i atrakcji. Obserwujcie nasz profil, a już wkrótce podzielimy się z Wami szczegółami!',
        'Dziękujemy, że jesteście z nami, tworzymy razem niepowtarzalne chwile!',
        'Informacje o warsztatach,',
        'Zapisy na warsztaty na stronie:',
        'www.ceramikanero.com',
        'Zapraszamy na warsztaty ,zapisy na www.ceramikanero.com',
        '26 wyświetleń',
      ],
      images: [
        {
          alt: '(no alt)',
          src: '/images/wix-migrated/747d6f_0296bb0269754a8295a47f62c62d4822.jpg',
          dims: '243x243',
        },
        {
          alt: 'Letnia akademia artystyczna całe wakacje',
          src: '/images/wix-migrated/747d6f_db20092f210148bdb5f759fb972dcbe1.jpg',
          dims: '289x162',
        },
        {
          alt: 'Dlaczego Warto Wybrać Naszą Pracownię Ceramiki dla Twoich Kreatywnych Potrzeb?',
          src: '/images/wix-migrated/747d6f_0a4d8816a90344e9a161a8f1af115f5f.png',
          dims: '289x162',
        },
      ],
      categoryHints: [],
    },
    {
      slug: 'glina-do-wina',
      route: '/post/glina-do-wina',
      title: 'Glina do wina',
      author: 'Gosia Nero',
      date: '15 kwi 2024',
      readingTime: '1 minut(y) czytania',
      paragraphs: [
        'Odkryj Twórczy Świat Ceramiki: Warsztaty w Pracowni Ceramiki Nero',
        'Wytwarzanie ceramiki to sztuka, która łączy w sobie pasję, precyzję i niepowtarzalność. W Pracowni Ceramiki Nero, położonej w malowniczym Suchym Lesie, ta sztuka staje się dostępna dla każdego, kto pragnie odkryć magiczny świat lepienia z gliny.',
        'Warsztaty organizowane przez Pracownię Ceramiki Nero to nie tylko okazja do stworzenia unikalnych dzieł, ale także podróż w świat kreatywności i inspiracji. Pod opieką doświadczonej instruktorki, uczestnicy mają szansę eksperymentować z różnymi technikami formowania, od podstawowych po zaawansowane, tworząc przy tym swoje własne, niepowtarzalne dzieła.',
        'Atmosfera warsztatów jest niezwykła. Pracownia otoczona jest inspirującym otoczeniem, sprzyjającym koncentracji i rozwijaniu kreatywności. Dodatkowo, delikatne dźwięki włoskiej muzyki tworzą niezapomnianą aurę, sprawiając, że każdy moment spędzony tutaj staje się wyjątkowy.',
        'Ale to nie wszystko! Dodatkowym smaczkiem warsztatów jest degustacja wina i włoskich przystawek, które dodają wydarzeniu wyjątkowego charakteru i umożliwiają uczestnikom relaks i rozmowę w miłej atmosferze.',
        'Warsztaty w Pracowni Ceramiki Nero są dostosowane do różnych poziomów zaawansowania, co oznacza, że każdy, bez względu na swoje doświadczenie, może znaleźć coś dla siebie. Dla tych, którzy nie mogą uczestniczyć w procesie szkliwienia, istnieje możliwość skorzystania z usługi szkliwienia przez pracownię, zapewniając kompleksową opiekę nad ich dziełami.',
        'Cena warsztatów jest więcej niż uczciwa, biorąc pod uwagę wszystkie zapewniane materiały, degustację i profesjonalne prowadzenie. Rezerwacja miejsca jest prosta i szybka, a po dokonaniu rezerwacji, uczestnik otrzymuje potwierdzenie wraz z informacjami dotyczącymi płatności.',
        'Jeśli szukasz sposobu na rozwinięcie swojej kreatywności, relaksujący sposób na spędzenie czasu lub po prostu chcesz doświadczyć magii tworzenia ceramiki, warsztaty w Pracowni Ceramiki Nero są idealnym wyborem. Odkryj swoją artystyczną duszę i dołącz do naszej kreatywnej społeczności już dziś!',
      ],
      images: [
        {
          alt: '(no alt)',
          src: '/images/wix-migrated/747d6f_e9ae4fd07ea84670a4619d707e66e83e.png',
          dims: '938x350',
        },
        {
          alt: 'Letnia akademia artystyczna całe wakacje',
          src: '/images/wix-migrated/747d6f_db20092f210148bdb5f759fb972dcbe1.jpg',
          dims: '289x162',
        },
        {
          alt: 'Dlaczego Warto Wybrać Naszą Pracownię Ceramiki dla Twoich Kreatywnych Potrzeb?',
          src: '/images/wix-migrated/747d6f_0a4d8816a90344e9a161a8f1af115f5f.png',
          dims: '289x162',
        },
      ],
      categoryHints: [],
    },
    {
      slug: 'jak-zacząć-przygodę-z-ceramiką',
      route: '/post/jak-zacząć-przygodę-z-ceramiką',
      title: 'Jak zacząć przygodę z ceramiką ?',
      author: 'Gosia Nero',
      date: '7 sty 2024',
      readingTime: '1 minut(y) czytania',
      paragraphs: [
        'Zaktualizowano: 3 kwi 2024',
        'Rozpoczęcie przygody z ceramiką to fascynujący krok w świat rękodzieła, który pozwala na wyrażanie kreatywności poprzez formowanie i tworzenie trwałych dzieł sztuki. Oto kilka kroków, które mogą pomóc Ci rozpocząć tę pasjonującą podróż:',
        'Zdobądź Podstawowy Sprzęt:',
        'Zacznij od podstawowego wyposażenia, takiego jak glina, koła garncarskie, narzędzia do formowania i szkliwa. To podstawowe elementy, które pozwolą Ci stworzyć pierwsze projekty.',
        'Znajdź Inspiracje:',
        'Przeglądaj inspiracje online, czy to na Instagramie, Pinterest czy w książkach o ceramice. Znalezienie swojego stylu zainspiruje Cię do tworzenia unikalnych dzieł.',
        'Dołącz do Warsztatów lub Kursów:',
        'Zapisz się na lokalne warsztaty lub kursy ceramiki, aby zdobyć podstawowe umiejętności i poznać różne techniki. To także doskonała okazja do nawiązania kontaktów z innymi entuzjastami. Zapraszamy na na nasze warsztataty, oferta na stronie www.ceramikanero.com',
        'Eksperymentuj z Technikami:',
        'Nie bój się eksperymentować z różnymi technikami formowania i szkliwienia. To pozwoli Ci odkryć własny styl i unikalność w twoich projektach.',
        'Poznaj Podstawy Garncarstwa:',
        'Zrozumienie podstaw garncarstwa, takich jak centrowanie gliny na kole garncarskim czy formowanie odpowiednich kształtów, jest kluczowe dla sukcesu w ceramice.',
        'Stwórz Swój Kącik Twórczy:',
        'Zorganizuj swój kącik do pracy z gliną. Dostępność narzędzi i przestrzeń do pracy pozwoli Ci swobodnie rozwijać swoje projekty.',
        'Bądź Cierpliwy i Rzetelny:',
        'Ceramika wymaga cierpliwości. Bądź gotowy na sukcesy i porażki, a każdy projekt będzie dla Ciebie cennym doświadczeniem.',
        'Pamiętaj, że ceramika to nie tylko sztuka, ale także niekończąca się nauka. Rozwijaj się, eksperymentuj i ciesz się procesem tworzenia własnych, unikalnych dzieł. Powodzenia!',
        'Małgosia',
        'Pracownia ceramiki Nero',
        'ul. Podgórna 3',
        '62-002 Suchy Las',
        'www.ceramikanero.com',
        'FB/Instagram ceramika nero',
        'tel. 532 279 101',
        'mail kontakt@ceramikanero.pl',
        '38 wyświetleń',
      ],
      images: [
        {
          alt: '(no alt)',
          src: '/images/wix-migrated/747d6f_40f47e03350d4ef3b3d3e3c951eff7cb.jpg',
          dims: '938x350',
        },
        {
          alt: '(no alt)',
          src: '/images/wix-migrated/747d6f_25f701d5db584b2cabcec04bba397ec5.jpeg',
          dims: '243x243',
        },
        {
          alt: '(no alt)',
          src: '/images/wix-migrated/747d6f_439e4c293ab04730a3204fb223f7c0c9.jpg',
          dims: '244x243',
        },
        {
          alt: '(no alt)',
          src: '/images/wix-migrated/747d6f_d1a7cda543f04bfa93539ffe6925026b.jpg',
          dims: '243x243',
        },
        {
          alt: 'Letnia akademia artystyczna całe wakacje',
          src: '/images/wix-migrated/747d6f_db20092f210148bdb5f759fb972dcbe1.jpg',
          dims: '289x162',
        },
        {
          alt: 'Dlaczego Warto Wybrać Naszą Pracownię Ceramiki dla Twoich Kreatywnych Potrzeb?',
          src: '/images/wix-migrated/747d6f_0a4d8816a90344e9a161a8f1af115f5f.png',
          dims: '289x162',
        },
      ],
      categoryHints: [],
    },
    {
      slug: 'letnia-akademia-artystyczna-całe-wakacje',
      route: '/post/letnia-akademia-artystyczna-całe-wakacje',
      title: 'Letnia akademia artystyczna całe wakacje',
      author: 'Gosia Nero',
      date: null,
      readingTime: '1 minut(y) czytania',
      paragraphs: [
        '10 lip',
        'nauka malowania i lepienia z gliny dla Twojego dziecka w wakacje w Suchym Lesie',
        'Zapisz swoje dziecko na letnią akademię artystyczną - wybierz dowolny termin na naszej stronie www.ceramikanero.com',
        'To 2 godziny wspólnego malowani i lepienia z gliny',
        'Zajęcia dla dzieci od lat 6 do 15.',
        'Przyjdź i poznaj naszą pracownię.',
        'Zapraszamy',
        '3 wyświetlenia',
      ],
      images: [
        {
          alt: 'nauka malowania i lepienia z gliny dla Twojego dziecka w wakacje w Suchym Lesie',
          src: '/images/wix-migrated/747d6f_db20092f210148bdb5f759fb972dcbe1.jpg',
          dims: '740x490',
        },
        {
          alt: 'Dlaczego Warto Wybrać Naszą Pracownię Ceramiki dla Twoich Kreatywnych Potrzeb?',
          src: '/images/wix-migrated/747d6f_0a4d8816a90344e9a161a8f1af115f5f.png',
          dims: '289x162',
        },
        {
          alt: 'Czym zajmuje się Pracownia Ceramiki NERO?',
          src: '/images/wix-migrated/747d6f_bf6fc0998d4a4467945a89a8340eb7cd.png',
          dims: '289x162',
        },
      ],
      categoryHints: [],
    },
    {
      slug: 'nowe-warsztaty-ceramika-dla-smyka',
      route: '/post/nowe-warsztaty-ceramika-dla-smyka',
      title: 'Nowe warsztaty Ceramika dla smyka',
      author: 'Gosia Nero',
      date: '16 gru 2024',
      readingTime: '1 minut(y) czytania',
      paragraphs: [
        'Ceramika dla Smyka – Kreatywna zabawa z gliną!',
        'Wiele osób się o nie pytało- i tak, mamy warsztaty ceramiczne, nie jako stały kurs ale takie żeby Twoje dziecko mogło przyjść, poznać cały proces.',
        'Zapraszamy dzieci w wieku 6-15 lat na dwuczęściowe warsztaty ceramiczne, które łączą zabawę z nauką tworzenia wyjątkowych prac z gliny!',
        '🧡 Jak to działa?1️⃣ Lepienie – Na pierwszym spotkaniu dzieci tworzą swoje prace według tematu.2️⃣ Szkliwienie – Po dwóch tygodniach ozdabiają wypalone prace kolorowymi szkliwami.(Możliwość szkliwienia w późniejszym terminie – nawet po miesiącu).',
        '🎨 Dlaczego warto?',
        'Rozwój kreatywności i zdolności manualnych.',
        'Nauka podstaw ceramiki w przystępnej formie.',
        'Własnoręcznie wykonane prace, które będą piękną pamiątką!',
        '🗓️ Szczegóły:📅 Kiedy: Co druga sobota, godz. 10:30-11:30 (start: 4 stycznia).💸 Cena: 190 zł (95 zł x 2 spotkania).📍 Gdzie: Pracownia Ceramiki Nero, ul. Podgórna 3, Suchy Las.⏳ Odbiór prac: Po ok. 2-3 tygodniach od szkliwienia.',
        '📢 Uwaga! Aby wziąć udział w warsztatach, konieczne jest dokonanie dwóch rezerwacji – na oba spotkania:1️⃣ Pierwsze spotkanie (lepienie z gliny).2️⃣ Drugie spotkanie (szkliwienie – dwa tygodnie później).',
        '🗓️ Terminy warsztatów w 2024 roku:',
        'Styczeń: 4 i 18 stycznia',
        'Luty: 1 i 15 lutego',
        'Marzec: 1 i 15 marca',
        'Kwiecień: 29 marca i 12 kwietnia',
        'Maj: 10 i 24 maja',
        '🕙 Godzina: Zawsze o 10:30',
        '🎟️ Rezerwacje:Rezerwuj dwa terminy od razu – to komplet warsztatów dla pełnego procesu tworzenia i szkliwienia. Bez dwóch spotkań dziecko nie ukończy swojej pracy!',
        '🌐 Zapisy online: www.ceramikanero.com',
        'Dołączcie do naszej ceramicznej przygody i stwórzcie coś wyjątkowego razem z nami! 🏺✨',
        '11 wyświetleń',
      ],
      images: [
        {
          alt: '(no alt)',
          src: '/images/wix-migrated/11062b_eb2cf4d2cd5646fa8cfa980723ac63c7.jpg',
          dims: '740x493',
        },
        {
          alt: 'Letnia akademia artystyczna całe wakacje',
          src: '/images/wix-migrated/747d6f_db20092f210148bdb5f759fb972dcbe1.jpg',
          dims: '289x162',
        },
        {
          alt: 'Dlaczego Warto Wybrać Naszą Pracownię Ceramiki dla Twoich Kreatywnych Potrzeb?',
          src: '/images/wix-migrated/747d6f_0a4d8816a90344e9a161a8f1af115f5f.png',
          dims: '289x162',
        },
      ],
      categoryHints: [],
    },
    {
      slug: 'nowe-warsztaty-ceramika-dla-smyka-od-stycznia-2025',
      route: '/post/nowe-warsztaty-ceramika-dla-smyka-od-stycznia-2025',
      title: 'Nowe warsztaty Ceramika dla smyka od stycznia 2025',
      author: 'Gosia Nero',
      date: '30 gru 2024',
      readingTime: '1 minut(y) czytania',
      paragraphs: [
        'Twórcza zabawa dla dzieci – Ceramika dla Smyka',
        'Chcesz, żeby Twoje dziecko spróbowało czegoś nowego i rozwijało kreatywność? 🧡',
        'Zapraszamy na Ceramikę dla Smyka – dwuczęściowe warsztaty dla dzieci 6-15 lat!',
        '👩‍🎨 Co w programie?',
        '➡️ Spotkanie 1: Lepienie – tworzymy prace z gliny.',
        '➡️ Spotkanie 2: Szkliwienie – dodajemy kolory i blask.',
        '📅 Najbliższe terminy:',
        '4 stycznia, godz. 10:30',
        '18 stycznia , godz. 10:30',
        '🗓️ Jeśli szkliwienie nie może odbyć się po dwóch tygodniach, można je przełożyć nawet o miesiąc!',
        'Zapisz się teraz – liczba miejsc ograniczona! 🖌️',
        '9 wyświetleń',
      ],
      images: [
        {
          alt: '(no alt)',
          src: '/images/wix-migrated/747d6f_6fba4cab7fda46208092419846e777a4.png',
          dims: '740x620',
        },
        {
          alt: 'Letnia akademia artystyczna całe wakacje',
          src: '/images/wix-migrated/747d6f_db20092f210148bdb5f759fb972dcbe1.jpg',
          dims: '289x162',
        },
        {
          alt: 'Dlaczego Warto Wybrać Naszą Pracownię Ceramiki dla Twoich Kreatywnych Potrzeb?',
          src: '/images/wix-migrated/747d6f_0a4d8816a90344e9a161a8f1af115f5f.png',
          dims: '289x162',
        },
      ],
      categoryHints: [],
    },
    {
      slug: 'o-mnie',
      route: '/post/o-mnie',
      title: 'Mam na imię Małgosia i jestem pasjonatką sztuki ceramicznej',
      author: 'Gosia Nero',
      date: '2 sie 2023',
      readingTime: '2 minut(y) czytania',
      paragraphs: [
        'Zaktualizowano: 19 maj 2025',
        'Witaj na stronie Pracowni Ceramiki NERO!',
        'Nazywam się Małgosia Nero i jestem pasjonatką sztuki ceramicznej. Ta pracownia to moje miejsce na ziemi – przestrzeń, w której tworzę unikalne i piękne dzieła z gliny.',
        'Moja przygoda z ceramiką zaczęła się już we wczesnych latach i z czasem przerodziła się w prawdziwą życiową pasję. Uwielbiam eksperymentować z różnymi technikami i stylami, dzięki czemu moje prace są różnorodne i pełne wyrazu. Tworzenie z gliny to dla mnie nie tylko rzemiosło, ale przede wszystkim sposób wyrażania artystycznej duszy.',
        'W mojej pracowni znajdziesz zarówno ręcznie lepione przedmioty, jak i te wykonane na kole garncarskim. Oferuję szeroki wybór produktów – od funkcjonalnych naczyń po dekoracyjne rzeźby, które mogą stać się wyjątkową ozdobą Twojego domu lub oryginalnym prezentem dla bliskiej osoby.',
        'Inspiruje mnie natura, formy organiczne oraz piękno codzienności. Staram się, aby moje prace niosły ze sobą harmonię i spokój – wartości, które kryją się w ceramicznych formach.',
        'Każdy przedmiot w mojej pracowni powstaje ręcznie, z ogromną dbałością o detale. Nieustannie rozwijam swoje umiejętności, biorąc udział w warsztatach i wystawach. Dzięki temu mogę oferować prace, które łączą tradycję z nowoczesnością i spełniają najwyższe standardy jakości.',
        'Jeśli jesteś zainteresowany(a) zakupem moich prac – zapraszam do zapoznania się z portfolio, które znajdziesz na tej stronie.',
        'Chciał(a)byś wziąć udział w warsztatach? Odwiedź zakładkę Warsztaty, gdzie znajdziesz aktualną ofertę. Istnieje również możliwość zorganizowania warsztatów indywidualnych – specjalnie dla Ciebie!',
        'Dziękuję za odwiedzenie mojej pracowni. Zapraszam do śledzenia mojej twórczej podróży tutaj oraz w mediach społecznościowych. Jeśli masz pytania lub chcesz dowiedzieć się więcej o mojej pracy – skontaktuj się ze mną, z przyjemnością odpowiem.',
        'Serdecznie zapraszam do odkrywania magicznego świata ceramiki razem ze mną!Małgosia Nero z Suchego Lasu pod Poznaniem',
        '46 wyświetleń',
      ],
      images: [],
      categoryHints: [],
    },
    {
      slug: 'o-sklepie-z-ceramiką',
      route: '/post/o-sklepie-z-ceramiką',
      title:
        'O sklepie z ceramiką ręcznie wykonaną i poszliwioną w Pracowni ceramiki NERO',
      author: 'Gosia Nero',
      date: '6 sie 2023',
      readingTime: '1 minut(y) czytania',
      paragraphs: [
        'Zaktualizowano: 7 sie 2023',
        'Witam w mojej Pracowni Ceramiki',
        'Pracowni ceramiki NERO to miejsce, w którym powstają unikatowe rękodzieła z miłością do sztuki ceramicznej.',
        'Wizja i misja:',
        'Moją wizją jest przekazywanie tradycji ceramiki, jednocześnie łącząc ją z nowoczesnym podejściem do wzornictwa. Moje wyroby mają wprowadzać piękno i wyjątkowy charakter do domów moich Klientów, dodając im ciepła i elegancji.',
        'Moje produkty: W ofercie naszej pracowni znajdziesz szeroki wybór ceramiki artystycznej, ręcznie wykonanej.',
        'Oferujemy:',
        'Wazony, misy i naczynia ozdobne',
        'Kieliszki, kubki i filiżanki',
        'Figurki i rzeźby ceramiczne',
        'Kafle dekoracyjne',
        'Ozdoby ogrodowe i wiele więcej.',
        'Proces tworzenia:',
        'Każdy nasz produkt jest wynikiem starannego i kunsztownego procesu tworzenia. Moja ceramika powstaje w tradycyjny sposób, stosując sprawdzone techniki rzemieślnicze i dbałość o najmniejszy detal. Ręczne malowanie i szkliwienie sprawiają, że każdy element jest wyjątkowy.',
        'Zajęcia ceramiczne:',
        'Chcę podzielić się moją pasją z innymi. Organizuję warsztaty ceramiczne dla osób w mojej pracowni, gdzie uczestnicy mogą nauczyć się podstaw techniki ceramiki i wykonać swoje własne dzieła sztuki.',
        'Kontakt:',
        'Jeśli masz jakiekolwiek pytania lub jesteś zainteresowany naszymi wyrobami lub warsztatami, skontaktuj się z mną poprzez mailaila lub bezpośrednio pod podanym numerem telefonu. Chętnie odpowiem na wszystkie zapytania i pomożemy w realizacji Twoich potrzeb wziązanych z ceramiką.',
        'Zapraszam serdecznie do mojej pracowni ceramiki, gdzie sztuka łączy się z funkcjonalnością, a tradycja spotyka się z nowoczesnością.',
        'Cieszę się, że mogę podzielić się moją pasją z Tobą!',
        '37 wyświetleń',
      ],
      images: [
        {
          alt: '(no alt)',
          src: '/images/wix-migrated/de27b2e088814fa994ff8a44f2a9a467.jpg',
          dims: '113x113',
        },
        {
          alt: '(no alt)',
          src: '/images/wix-migrated/87a0d537f3654d148ba517d045f6d3ff.jpg',
          dims: '113x113',
        },
        {
          alt: '(no alt)',
          src: '/images/wix-migrated/25189b4996b84d5ba2cd03f12eff06c5.jpg',
          dims: '243x243',
        },
        {
          alt: '(no alt)',
          src: '/images/wix-migrated/747d6f_b36c26d927764d3f859565bb328d0dae.jpg',
          dims: '244x243',
        },
        {
          alt: '(no alt)',
          src: '/images/wix-migrated/11062b_9fca2391b3524803822fb730e5d8ac1b.jpg',
          dims: '243x243',
        },
        {
          alt: 'Letnia akademia artystyczna całe wakacje',
          src: '/images/wix-migrated/747d6f_db20092f210148bdb5f759fb972dcbe1.jpg',
          dims: '289x162',
        },
        {
          alt: 'Dlaczego Warto Wybrać Naszą Pracownię Ceramiki dla Twoich Kreatywnych Potrzeb?',
          src: '/images/wix-migrated/747d6f_0a4d8816a90344e9a161a8f1af115f5f.png',
          dims: '289x162',
        },
      ],
      categoryHints: [],
    },
    {
      slug: 'pikniki-artystyczne-na-polanie-przed-pracownią-ceramiki-nero',
      route:
        '/post/pikniki-artystyczne-na-polanie-przed-pracownią-ceramiki-nero',
      title: 'Pikniki artystyczne na polanie przed Pracownią ceramiki Nero',
      author: 'Gosia Nero',
      date: '19 maj 2025',
      readingTime: '1 minut(y) czytania',
      paragraphs: [
        'Zapraszamy na "Piknik artystyczny w Pracowni ceramiki Nero".',
        'Jest to świetna okazja, żeby nas poznać.',
        'Zawsze zaczynamy warsztatami ceramicznymi "Ceramika dla smyka", które starują o 10.30. Wymagają zapisania się przez stronę internetową: www.ceramikanero.com zakładka: "zapisy"',
        'Po warsztatach zaczynamy wspólne biesiadowanie na polu przed pracownią.',
        'Będzie palenisko: zabierzcie ze sobą kiełbaski i inne smakołyki do usmażenia na ogniu oraz napoje.',
        'Weźcie też kocyk, aby usiąść na trawie i spędzić czas w gronie najbliższych. Sprawdź terminy Pikników na naszej stronie i dołącz do nas .',
        'Najbliższy już 26 maja,',
        'Podczas każdego pikniku będą atrakcje dla dużych i małych: teraz będzie możliwość ulepienia serduszka z okazji dnia mamy z ceramiki. Dodatkowo płątne 30 zł. plus kto ma ochotę zostawić pracę do wypału to w sumie: warsztaty plus wypał 60 zł.',
        'Dzieci będą tworzyły mural na ścianie.',
        'Wstęp na na naszą imprezę jest bezpłatny ! zapraszamy każdego w każdym wieku do wspólnego piknikowania !',
        'Przez cały piknik będziemy też wspólnie kolorować wielką, słoneczną łąkę kwiatową dla naszych pięknych Mam! 🌼 A dla Mam – i wszystkich, którzy szukają odpoczynku od zgiełku miasta – przygotowaliśmy miejsce na relaks na naszej polanie.',
        '☀️ Zapraszamy oczywiście także Tatusiów i całe rodziny! 🧺 Zabierzcie ze sobą koce piknikowe, kiełbaski na palenisko i dużo dobrego humoru! Wstęp na piknik jest darmowy, płatne są tylko wybrane warsztaty i zajęcia. 📩 Kontakt: kontakt@ceramikanero.pl',
        '📞 Tel. 532 279 101 🌐 Strona i zapisy: www.ceramikanero.com Nie może Was zabraknąć – będzie kolorowo, twórczo i bardzo rodzinnie! 🧡',
        'kolejne terminy na wakacje:',
        '7 czerwca, 5 lipca, 9 sierpnia, 30 sierpnia',
        'Zapraszamy i do zobaczenia !',
        '10 wyświetleń',
      ],
      images: [
        {
          alt: '(no alt)',
          src: '/images/wix-migrated/747d6f_5fbe376ba5bd4db9a9118927f037d80d.jpg',
          dims: '740x494',
        },
        {
          alt: 'Letnia akademia artystyczna całe wakacje',
          src: '/images/wix-migrated/747d6f_db20092f210148bdb5f759fb972dcbe1.jpg',
          dims: '289x162',
        },
        {
          alt: 'Dlaczego Warto Wybrać Naszą Pracownię Ceramiki dla Twoich Kreatywnych Potrzeb?',
          src: '/images/wix-migrated/747d6f_0a4d8816a90344e9a161a8f1af115f5f.png',
          dims: '289x162',
        },
      ],
      categoryHints: [],
    },
    {
      slug: 'slow-design-co-oznacza',
      route: '/post/slow-design-co-oznacza',
      title: 'Najpopularniejsze style wnętrzarskie',
      author: 'Gosia Nero',
      date: '2 sie 2023',
      readingTime: '2 minut(y) czytania',
      paragraphs: [
        'Zaktualizowano: 6 sie 2023',
        'Najpopularniejsze style wnętrzarskie zmieniają się wraz z upływem czasu, ale w 2021 roku kilka stylów było szczególnie popularnych. Oczywiście, sytuacja może się zmienić w przyszłości, ale poniżej przedstawiam kilka trendów wnętrzarskich, które były popularne do 2021 roku:',
        'Minimalizm: Styl minimalistyczny jest bardzo popularny i polega na prostocie, czystych liniach i ograniczonej ilości elementów dekoracyjnych. Pomieszczenia są utrzymane w neutralnych kolorach, a przestrzeń jest starannie zaplanowana, aby unikać zbędnych ozdobników.',
        'Skandynawski: Wywodzący się z krajów skandynawskich, ten styl jest ceniony za swoją funkcjonalność, jasne kolory, naturalne materiały i dbałość o detal. Jasne drewno, białe ściany, minimalistyczne meble i dużo światła są charakterystycznymi cechami tego stylu.',
        'Nowoczesny: Styl nowoczesny ma swoje korzenie w modernizmie i cechuje się przede wszystkim prostymi liniami, wyrazistymi formami i innowacyjnymi rozwiązaniami. Wnętrza tego typu są często utrzymane w stonowanych kolorach, a meble i akcesoria są nowoczesne i ergonomiczne.',
        'Rustykalny:',
        'Styl rustykalny czerpie inspirację z wiejskich, wiejskich domów i charakteryzuje się naturalnymi materiałami, takimi jak drewno, kamień czy ceramika. Wnętrza są przytulne, często zdobione ręcznie wykonanymi elementami i ozdobione w stylu wiejskim.',
        '5. Eklektyczny: Ten styl łączy różne elementy i inspiracje z różnych epok i kultur. Wnętrza eklektyczne są często pełne kolorów, wzorów i niekonwencjonalnych rozwiązań, co daje im wyjątkowy i oryginalny charakter.',
        '6. Industrialny: Styl industrialny czerpie z estetyki przemysłowej, wykorzystując surowe materiały, takie jak metal, beton i cegła. Charakteryzuje się odsłoniętymi instalacjami, dużymi przestrzeniami i surowym, surowym wyglądem.',
        '7. Vintage i retro: Styl vintage i retro cieszy się popularnością, zwłaszcza wśród miłośników starego stylu. Obejmuje on wykorzystanie mebli, dodatków i dekoracji z przeszłości, które dodają wnętrzu nostalgii i charakteru.',
        'Warto zaznaczyć, że styl wnętrzarski jest indywidualną kwestią gustu, a wiele osób preferuje łączenie różnych stylów w celu stworzenia unikatowego wystroju. Wraz z mijającymi latami i zmieniającymi się trendami, modne style wnętrzarskie mogą',
        'się zmieniać, dlatego warto być świadomym nowych inspiracji i możliwości aranżacyjnych.',
        '19 wyświetleń',
      ],
      images: [
        {
          alt: '(no alt)',
          src: '/images/wix-migrated/b0c1743eec4b7984c4c5d8a5727dc0b4.jpg',
          dims: '388x259',
        },
        {
          alt: '(no alt)',
          src: '/images/wix-migrated/11062b_21dbdd79270a44b8abe0d6177d2ac1f9.jpg',
          dims: '280x157',
        },
        {
          alt: '(no alt)',
          src: '/images/wix-migrated/11062b_30c5ffa57f61439aa48f705fe3d49dd8.jpg',
          dims: '243x243',
        },
        {
          alt: 'Dlaczego warsztaty z gliny? Wpływ pracy z gliną na człowieka. Rzemiosło.',
          src: '/images/wix-migrated/595cb32628cf4476abc9c0d74e063e07.jpg',
          dims: '289x162',
        },
      ],
      categoryHints: [],
    },
    {
      slug: 'startujemy-z-zapisamy-na-wrzesień-bogata-oferta-warsztatów-dla-dzieci-rysunek-malarstwo-ceramika',
      route:
        '/post/startujemy-z-zapisamy-na-wrzesień-bogata-oferta-warsztatów-dla-dzieci-rysunek-malarstwo-ceramika',
      title:
        'Startujemy z zapisamy na wrzesień! Bogata oferta warsztatów dla dzieci Rysunek, malarstwo, ceramika, Sensoceramika, Architektura',
      author: 'Gosia Nero',
      date: '14 sie 2025',
      readingTime: '2 minut(y) czytania',
      paragraphs: [
        'Kursy Rysunku, Malarstwa i Ceramiki w Suchym Lesie – Zapisz się na Nowy Rok Szkolny',
        'Chcesz rozwijać artystyczne talenty swojego dziecka? Zapraszamy do Pracowni Ceramiki NERO w Suchym Lesie, gdzie oferujemy kursy rysunku, malarstwa i ceramiki dla dzieci i młodzieży w różnym wieku. Zajęcia odbywają się w przyjaznej atmosferze i są prowadzone przez doświadczonych instruktorów.',
        'Zapisy obowiązują na cały rok szkolny. Po pierwszych dwóch zajęciach możesz podjąć decyzję o kontynuacji i podpisaniu umowy.',
        '📅 Harmonogram zajęć',
        'Harmonogram zajęć',
        'Rodzaj zajęć',
        'Wiek',
        'Poziom',
        'Dzień tygodnia',
        'Godziny',
        'Rysunek • Malarstwo • Ceramika',
        '6–10 lat',
        'Poniedziałek',
        '16:00–17:10',
        'Wtorek',
        '17:15–18:25',
        'Czwartek',
        '16:00–17:10',
        'Sensoceramika',
        '6–10 lat',
        'Wtorek',
        '16:00–17:10',
        'Środa',
        '16:00–17:10',
        'Rysunek • Malarstwo • Ceramika',
        '11+ lat',
        'Czwartek',
        '17:15–18:45',
        'Ceramika',
        '11+ lat',
        'Podstawowy',
        'Wtorek',
        '17:15–18:25',
        'Ceramika',
        '11+ lat',
        'Średniozaawansowany',
        'Poniedziałek',
        '17:15–18:45',
        'Rysunek i Architektura',
        '11+ lat',
        'Poniedziałek',
        '17:15–18:45',
        'Czwartek',
        '17:15–18:45',
        '🖌 Opisy zajęć w Pracowni Ceramiki NERO',
        'Nasze kursy to połączenie twórczej zabawy, nauki nowych technik i rozwijania pasji do sztuki. Poniżej znajdziesz szczegółowy opis zajęć dla różnych grup wiekowych.',
        '🎨 Rysunek • Malarstwo • Ceramika (6–10 lat)',
        'Kolorowa podróż przez świat sztuki!Dzieci uczą się rysunku, malarstwa i pracy z gliną, poznają różne techniki oraz style artystyczne. Zajęcia rozwijają kreatywność, wyobraźnię i zdolności manualne, a także pozwalają odkryć indywidualny styl twórczy.',
        '🖐 Sensoceramika (6–10 lat)',
        'Zabawa sensoryczna połączona z pracą w glinie i masach plastycznych.Uczestnicy poznają różnorodne faktury i materiały, tworząc mozaiki, rzeźby oraz unikalne projekty artystyczne. Zajęcia wspierają rozwój zmysłów i sprawności manualnej w kreatywny sposób.',
        '🎨 Rysunek • Malarstwo • Ceramika (11+ lat)',
        'Rozwój umiejętności plastycznych i ceramicznych dla starszych dzieci.Od rysunku ołówkiem, przez malarstwo, aż po zaawansowane projekty ceramiczne — uczestnicy poznają bogaty wachlarz technik i form twórczych.',
        '🏺 Ceramika – poziom podstawowy (11+ lat)',
        'Idealny start dla początkujących.Dzieci uczą się podstawowych technik lepienia, dekorowania i szkliwienia, a na koniec tworzą swoje pierwsze autorskie prace ceramiczne.',
        '🏺 Ceramika – poziom średniozaawansowany (11+ lat)',
        'Dla tych, którzy mają już doświadczenie.Na zajęciach skupiamy się na pracy na kole garncarskim, tworzeniu bardziej złożonych form, dekoracjach wielowarstwowych i indywidualnych projektach artystycznych.',
        '🏛 Rysunek i Architektura (11+ lat)',
        'Połączenie sztuki i projektowania.Uczestnicy poznają zasady perspektywy, kompozycji i rysunku architektonicznego, a następnie tworzą własne projekty budynków, wnętrz i detali architektonicznych.',
        '📌 Dlaczego warto wybrać nasze zajęcia?',
        'Małe grupy i indywidualne podejście',
        'Praca w profesjonalnie wyposażonej pracowni',
        'Rozwój talentów i kreatywności w przyjaznej atmosferze',
        '📞 Zapisy i informacje',
        'Telefon: 532 279 101',
        'E-mail: kontakt@ceramikanero.pl',
        'Formularz zapisów: www.ceramikanero.pl',
        'Serdecznie zapraszamy do wspólnej artystycznej przygody! Zespół Pracowni Ceramiki NERO 🎨🖌️',
        '16 wyświetleń',
      ],
      images: [
        {
          alt: '(no alt)',
          src: '/images/wix-migrated/747d6f_71c100aa03c04a2393e0deb186d0dfe1.jpg',
          dims: '243x243',
        },
        {
          alt: '(no alt)',
          src: '/images/wix-migrated/747d6f_565523d2b38546f582a8ddb7f0a5dd67.jpg',
          dims: '244x243',
        },
        {
          alt: '(no alt)',
          src: '/images/wix-migrated/747d6f_8af7f884525642d8b67fe0bf709a577b.png',
          dims: '243x243',
        },
        {
          alt: '(no alt)',
          src: '/images/wix-migrated/747d6f_5cee2d3c27734c998452e5eae7fdfb6e.jpg',
          dims: '243x243',
        },
        {
          alt: '(no alt)',
          src: '/images/wix-migrated/747d6f_2234cc741bd5422eb5d92705a021219a.jpg',
          dims: '244x243',
        },
        {
          alt: '(no alt)',
          src: '/images/wix-migrated/747d6f_5946cd9b03e84e5c8439772d49367b12.jpg',
          dims: '243x243',
        },
        {
          alt: 'Letnia akademia artystyczna całe wakacje',
          src: '/images/wix-migrated/747d6f_db20092f210148bdb5f759fb972dcbe1.jpg',
          dims: '289x162',
        },
        {
          alt: 'Dlaczego Warto Wybrać Naszą Pracownię Ceramiki dla Twoich Kreatywnych Potrzeb?',
          src: '/images/wix-migrated/747d6f_0a4d8816a90344e9a161a8f1af115f5f.png',
          dims: '289x162',
        },
        {
          alt: 'Czym zajmuje się Pracownia Ceramiki NERO?',
          src: '/images/wix-migrated/747d6f_bf6fc0998d4a4467945a89a8340eb7cd.png',
          dims: '289x162',
        },
      ],
      categoryHints: [],
    },
    {
      slug: 'twój-tytuł-jak-nazwałbyś-swój-przepis',
      route: '/post/twój-tytuł-jak-nazwałbyś-swój-przepis',
      title: 'Jak dekorować dom na jesień?',
      author: 'Gosia Nero',
      date: '29 wrz 2023',
      readingTime: '1 minut(y) czytania',
      paragraphs: [
        'Na jesień można wprowadzić do domu wiele ciepłych i przytulnych elementów, aby stworzyć atmosferę pełną tego magicznego sezonu. Oto kilka pomysłów:',
        'Kolory jesieni: Dodaj do wnętrza ciepłe, ziemiaste kolory, takie jak pomarańcz, czerwień, brąz i żółć. Możesz to zrobić poprzez dodanie poduszek, pledów, obrusów czy dekoracji.',
        'Liście i gałęzie: Zbieraj kolorowe liście i gałęzie na spacerach i używaj ich do dekoracji. Możesz umieścić je w wazonach lub stworzyć wianki.',
        'Świece: Zapachowe świece o aromatach jesieni (jak jabłko, cynamon czy dynia) dodadzą nie tylko pięknego światła, ale także przyjemnego zapachu.',
        'Dynie i dynie ozdobne: To klasyczny element jesiennej dekoracji. Postaw na kolorowe dynie na parapecie lub stwórz z nich aranżacje na stole.',
        'Tekstylia: Zmieniaj lekkie, letnie tekstylia na grubsze i cieplejsze. Płyny, poduszki z grubszego materiału, pledy - wszystko to sprawi, że dom będzie bardziej przytulny.',
        'Mapy i zdjęcia: Jeśli lubisz DIY, stwórz mapy jesienne z liści albo zrób zdjęcia w parku pełnym jesiennych barw.',
        'Owocowe akcenty: Postaw na owoce sezonowe, takie jak jabłka czy gruszki, jako element dekoracji. Mogą być zarówno na stole, jak i w koszach.',
        'Sztuczne ognie: Jeśli masz komin, to świetne miejsce na dekoracyjne drewno czy świeczki imitujące ogień. To doda ciepła i przytulności.',
        'Sztuczne zwierzęta: Jelenie, sowy czy jeże to zwierzęta kojarzące się z jesienią. Mogą być zarówno w postaci ozdób, jak i malunków czy zdjęć.',
        'Dekoracje na oknach: Ozdabiaj okna girlandami z liści, kolorowymi koronkami albo ozdobnymi kurtynami w odcieniach jesieni.',
        'Zapraszamy również do naszej pracowni, tu możesz stworzyć swoje spersonalizowane ozdoby do domu, które będą pasowały do twojego wnętrza i będziesz miał je na wiele lat.',
        '29 wyświetleń',
      ],
      images: [
        {
          alt: '(no alt)',
          src: '/images/wix-migrated/747d6f_ffa722856f6d45fcbf568b5e5bb50fbb.jpg',
          dims: '592x935',
        },
        {
          alt: 'Letnia akademia artystyczna całe wakacje',
          src: '/images/wix-migrated/747d6f_db20092f210148bdb5f759fb972dcbe1.jpg',
          dims: '289x162',
        },
        {
          alt: 'Dlaczego Warto Wybrać Naszą Pracownię Ceramiki dla Twoich Kreatywnych Potrzeb?',
          src: '/images/wix-migrated/747d6f_0a4d8816a90344e9a161a8f1af115f5f.png',
          dims: '289x162',
        },
      ],
      categoryHints: [],
    },
    {
      slug: 'warsztatyzgliny',
      route: '/post/warsztatyzgliny',
      title:
        'O warsztatach: lepienia z gliny dla dorosłych i dzieci, tworzymy małe dzieła sztuki, zabawa i relaks',
      author: 'Gosia Nero',
      date: '7 sie 2023',
      readingTime: '2 minut(y) czytania',
      paragraphs: [
        'Witamy na Naszych Warsztatach z lepienia z gliny',
        'Moje warsztaty lepienia z gliny w Pracowni ceramiki NERO to miejsce, gdzie możesz rozwinąć swoją kreatywność, odkryć magię rękodzieła i zanurzyć się w świecie ceramiki. Jestem osobą, która kocha dzielić się swoją miłością do gliny i prowadzić innych w niezwykłą podróż artystyczną.',
        'Wizja i misja:',
        'Moją wizją jest umożliwienie każdemu odkrycia swojego artystycznego potencjału poprzez praktykę lepienia z gliny. Moje warsztaty mają być miejscem inspiracji, rozwoju i tworzenia wyjątkowych dzieł sztuki, a także miejscem spotkań dobrych osób, oderwaniem sięod codziennej rzeczywistości. Jako mama i kobieta wiele lat pracująca w korporacji wiem ile enegii i wysiłku wymaga zorganizowanie dnia codziennego. Często po tygodniu godzenia pracy zawodowej z obowiązkami domowymi czujemy się wykończone i wyeksploatowane. Co z biegiem czasu może powodować długotrałe przemeczenie a nawet wywoływać choroby. Dlatego znajdźmy czas na regenerację.',
        'Zapraszam do artykułu na moim blogu na temat: jak wpływa praca z gliną na nasz mózg.',
        'Co oferuję:',
        'Moje warsztaty lepienia z gliny są dostępne dla osób w różnym wieku i poziomie zaawansowania. Oferujemy:',
        'Warsztaty dla dzieci: Zajęcia skierowane do najmłodszych od 7 roku życia, gdzie uczymy ich podstawowych technik lepienia i pozwalamy wyrazić ich wyobraźnię w formie glinianych kształtów. Z racji wykształcenia lingwistycznego, biegle posługujęsięjezykiem angielskim, niemieckim i włoskim wprowadzam teżelementy nauki podstaw tych języków oraz wiedzy a kulbliskich mojemu sercu krajów - Włoch, z których pochodzi mój mąż oraz Austrii, gdzie spędziłam wiele lat mojego życia. Warsztaty dla dzieci odbywają się od września do czerwca. Organizuję grupy już od 5 osób. Zorganizuj swoją grupę lub dołącz do aktualnych zajęć.',
        'Warsztaty dla dorosłych początkujących lub zaawansowanych: Glina do wina, Glina przyjaciele i rodzina - to wspólny czas dla dorosłych i starszych dzieci oraz warsztaty Ulep swój kubek. Szczegóły znajdują sięw zakładce warsztaty',
        'Proces tworzenia: Każdy uczestnik otrzymuje własny blok gliny oraz zestaw podstawowych narzędzi ceramika i ma możliwość wykonać swoje własne dzieło pod okiem instruktora. Uczę różnych technik lepienia, szkliwienia i dekorowania, aby stworzyć unikatowe dzieło sztuki.',
        'Terminy i zapisy:',
        'Na mojej stronie znajdziesz aktualny harmonogram warsztatów w zakładce warsztaty oraz dostępność miejsc. Zapisy są łatwe i wygodne - wystarczy wypełnić formularz online, dostaniesz maila potwierdzającego rezerwację oraz numer konta, na który należy uiścić całą wpłatę za warsztat w ciągu 24 h.',
        'Galeria na FACEBOOKu i INSTAGRAMie:',
        'Zapraszam do mediów społecznościowych FACEBOOK i INSTAGRAM, gdzie prezentuję przebieg i prace uczestników naszych warsztatów. Możesz zobaczyć różnorodność stylów i inspiracji oraz zainspirować się twórczością innych.',
        'Kontakt:',
        'Jeśli masz pytania, chciałbyś się dowiedzieć więcej o naszych warsztatach lub zarezerwować miejsce, skontaktuj się ze mną za pomocą formularza kontaktowego lub pod podanym numerem telefonu.',
        'Zapraszam na moje warsztaty lepienia z gliny, gdzie możesz odkryć magię tej wyjątkowej techniki, rozwijać swoje umiejętności artystyczne i cieszyć się tworzeniem własnych unikatowych dzieł ceramicznych.',
        'Dołącz do nas i stwórz coś pięknego!',
        '56 wyświetleń',
      ],
      images: [
        {
          alt: '(no alt)',
          src: '/images/wix-migrated/nsplsh_bb3bccc5280d4c56a81635bea456738b.jpg',
          dims: '143x215',
        },
        {
          alt: 'Letnia akademia artystyczna całe wakacje',
          src: '/images/wix-migrated/747d6f_db20092f210148bdb5f759fb972dcbe1.jpg',
          dims: '289x162',
        },
        {
          alt: 'Dlaczego Warto Wybrać Naszą Pracownię Ceramiki dla Twoich Kreatywnych Potrzeb?',
          src: '/images/wix-migrated/747d6f_0a4d8816a90344e9a161a8f1af115f5f.png',
          dims: '289x162',
        },
      ],
      categoryHints: [],
    },
    {
      slug: 'wpływ-pracy-z-gliną-na-człowieka',
      route: '/post/wpływ-pracy-z-gliną-na-człowieka',
      title:
        'Dlaczego warsztaty z gliny? Wpływ pracy z gliną na człowieka. Rzemiosło.',
      author: 'Gosia Nero',
      date: '2 sie 2023',
      readingTime: '1 minut(y) czytania',
      paragraphs: [
        'Zaktualizowano: 7 sie 2023',
        'Praca z gliną wpływa bardzo pozytywnie na nasz układ nerwowy.',
        'Praca z gliną, zwłaszcza w dziedzinie rzemiosła ceramicznego,wpływa bardzo pozytywnie. Oto niektóre z głównych aspektów wpływu pracy z gliną na człowieka:',
        'Kreatywność i samorealizacja: Praca z gliną może być dla wielu osób źródłem artystycznej ekspresji i kreatywności. Rzemiosło ceramiczne daje ludziom możliwość tworzenia unikalnych i pięknych dzieł, co przyczynia się do zwiększenia poczucia spełnienia i samorealizacji.',
        'Terapia i relaksacja: Wielu ludzi uznaje pracę z gliną za terapeutyczną i relaksującą. Dotykanie, modelowanie i tworzenie z gliny mogą pomóc w redukcji stresu, lęku i napięcia.',
        'Rozwój zdolności motorycznych: Manipulowanie gliną wymaga precyzji i kontroli ruchów, co może pomóc w rozwijaniu zdolności motorycznych i koordynacji ruchowej.',
        'Łączenie z tradycją: Ceramika ma długą historię i jest ważnym elementem wielu tradycji kulturowych. Praca z gliną może pomóc w zachowaniu dziedzictwa kulturowego i łączeniu się z przeszłością.',
        '31 wyświetleń',
      ],
      images: [
        {
          alt: '(no alt)',
          src: '/images/wix-migrated/595cb32628cf4476abc9c0d74e063e07.jpg',
          dims: '740x501',
        },
        {
          alt: 'Najpopularniejsze style wnętrzarskie',
          src: '/images/wix-migrated/b0c1743eec4b7984c4c5d8a5727dc0b4.jpg',
          dims: '289x162',
        },
      ],
      categoryHints: [],
    },
    {
      slug: 'wspaniała-historia-pracowni-od-miłości-do-gotowania-do-tworzenia-inspirującej-wspólnoty',
      route:
        '/post/wspaniała-historia-pracowni-od-miłości-do-gotowania-do-tworzenia-inspirującej-wspólnoty',
      title:
        'Wspaniała Historia Pracowni: Od Miłości do Gotowania do Tworzenia Inspirującej Wspólnoty',
      author: 'Gosia Nero',
      date: '14 lut 2024',
      readingTime: '2 minut(y) czytania',
      paragraphs: [
        'Dziś walentynki, dlatego postanowiłam podzielić się z Wami tą historią.',
        'Historia pracowni, którą zaczęłam wraz z moim mężem, Włochem, jest historią totalnej miłości i pasji do sztuki kulinarnej. Wszystko zaczęło się od wspólnych chwil spędzonych przy gotowaniu, podczas których tworzyliśmy smakowite potrawy i dzieliliśmy się nimi ze światem. Zainspirowani tą pasją postanowiliśmy stworzyć profil kulinarny, na którym prezentowaliśmy nie tylko przepyszne dania, ale również estetyczne aranżacje na talerzach i miseczkach.',
        'To właśnie wtedy zrodził się pomysł, aby zacząć tworzyć te estetyczne kompozycje samodzielnie. Zdjęcia naszych kulinarnych dzieł zaczęły zdobywać uznanie, co skłoniło mnie do rozważenia kontynuowania tej pasji samodzielnie. Tak narodziła się idea profilu, która na początku miała służyć jako mój indywidualny album ceramicznych eksperymentów, a z czasem przekształciła się w medium do komunikacji z szeroką publicznością.',
        'Pracownia stała się miejscem, gdzie nie tylko powstają estetyczne talerze, ale również ludzie odnajdują swoją duszę i spokój. To nie tylko przestrzeń do tworzenia, lecz także miejsce, w którym odzyskują kontakt ze sobą i odkrywają miłość do samych siebie. Każdy talerz stworzony w pracowni przenosi ze sobą nie tylko doznania, ale również emocje i pasję, które włożyłam w jego stworzenie.',
        'To fascynujące, jak ta mała pracownia stała się centrum inspiracji dla wielu ludzi. Dzięki niej poznałam mnóstwo cudownych osób, które podzielały moją pasję do gotowania i sztuki kulinarnej. Wspólne tworzenie, wymiana doświadczeń i radość płynąca z dzielenia się naszymi kulinarnymi eksperymentami sprawiły, że pracownia stała się nie tylko miejscem pracy, ale również miejscem, gdzie rodzą się nowe przyjaźnie i wspólne pasje.',
        'Nasza historia to nie tylko opowieść o gotowaniu i tworzeniu estetycznych dzieł, ale także o odkrywaniu piękna w prostocie, wyciszeniu w ruchu, i odnajdywaniu sensu życia w codziennych chwilach. To historie ludzi, którzy dzięki pracowni odzyskali miłość do samych siebie i odkryli nowe aspekty swojej kreatywności.',
        'Pracownia to nie tylko miejsce, gdzie powstają ceramiczne arcydzieła, ale także przestrzeń, gdzie kwitnie wspólnota ludzi z pasją. To niezwykła podróż od tworzenia sztuki z miłością do tworzenia inspirującej wspólnoty, gdzie każdy talerz jest nie tylko dziełem sztuki ceramicznej, ale również wyrazem miłości, pasji i wspólnego ducha twórczego. Czyż to nie cudowna historia?',
        '43 wyświetlenia',
      ],
      images: [
        {
          alt: '(no alt)',
          src: '/images/wix-migrated/747d6f_25f701d5db584b2cabcec04bba397ec5.jpeg',
          dims: '740x1110',
        },
        {
          alt: 'Letnia akademia artystyczna całe wakacje',
          src: '/images/wix-migrated/747d6f_db20092f210148bdb5f759fb972dcbe1.jpg',
          dims: '289x162',
        },
        {
          alt: 'Dlaczego Warto Wybrać Naszą Pracownię Ceramiki dla Twoich Kreatywnych Potrzeb?',
          src: '/images/wix-migrated/747d6f_0a4d8816a90344e9a161a8f1af115f5f.png',
          dims: '289x162',
        },
      ],
      categoryHints: [],
    },
    {
      slug: 'zaczynamy-nowe-warsztaty-już-we-wrześniu',
      route: '/post/zaczynamy-nowe-warsztaty-już-we-wrześniu',
      title:
        'Zaczynamy nowe warsztaty już we wrześniu. Śledź nasze media, jesteśmy na FACEBOOKu i INSTAGRAMie',
      author: 'Gosia Nero',
      date: '2 sie 2023',
      readingTime: '1 minut(y) czytania',
      paragraphs: [
        'Zaktualizowano: 7 sie 2023',
        'Zapraszamy do zapisywania się',
        'na nowe terminy.',
        'Nowy sezon zaczyna się już od września. W zakładce warsztaty można się juz zapisywać na pierwsze warsztaty.',
        'Zapraszam do śledzenia strony internetowej i mediów społecznościowych, a by być na bieżąco z nowo pojawiającymi sięwarsztatami i nowościami w Pracowni ceramiki NERO.',
        '24 wyświetlenia',
      ],
      images: [
        {
          alt: '(no alt)',
          src: '/images/wix-migrated/747d6f_6a39bd22cbe142c8a1aada6b04e8a120.jpg',
          dims: '243x243',
        },
        {
          alt: '(no alt)',
          src: '/images/wix-migrated/747d6f_b36c26d927764d3f859565bb328d0dae.jpg',
          dims: '244x243',
        },
        {
          alt: '(no alt)',
          src: '/images/wix-migrated/747d6f_c6bc037f500c42c986cc8ea2f3f4f0bc.jpg',
          dims: '243x243',
        },
      ],
      categoryHints: [],
    },
  ],
} as const;
