import type { SplitBlock } from '@/components/clone/marketing';

const IMG = {
  hero: '/images/wix-migrated/747d6f_11d47ff20fcf4afa9085b728719b20f0.jpg',
  logo: '/images/wix-migrated/747d6f_64bcccd9911949e7895d7325e88a5a75.png',
  badge: '/images/wix-migrated/747d6f_467152182e8a4089a2a18d1d71682254.png',
  kidsCourse:
    '/images/wix-migrated/747d6f_bd50a8f7389540819fdfd73395d3b559.jpg',
  kidsWorkshops:
    '/images/wix-migrated/747d6f_e1190fb32156413690b13225eff34e14.jpg',
  adults: '/images/wix-migrated/747d6f_6fc6a003b39840b58b4c14fa6e386e28.jpg',
  bridal: '/images/wix-migrated/747d6f_dfe2828f7bac463c873af8b1df79fe47.jpg',
  wine: '/images/wix-migrated/747d6f_db69baa543fb49fb8e204a00dc0016c6.jpg',
  firms: '/images/wix-migrated/747d6f_858ea5b1d9ce415c8d2ce2c3977c5d56.jpg',
  birthday: '/images/wix-migrated/747d6f_e0f7a1b2accc4542a5fec56b5ba4b975.jpg',
  family: '/images/wix-migrated/747d6f_431ea2ab2bee4c94b6e83dc97966c78a.png',
  paintBday: '/images/wix-migrated/747d6f_cd2460d4d3c1409b91c31dba9f7db804.png',
  schools: '/images/wix-migrated/747d6f_75125bb1ebef47b7939d3fbd6ec73f55.png',
} as const;

export const pracowniaPage = {
  title: 'Pracownia Ceramiki Suchy Las | Ceramika Nero',
  metaDescription:
    'Pracownia Ceramiki Nero to wyjątkowe miejsce, gdzie tradycja spotyka się z nowoczesnością, a pasja do ceramiki przeradza się w sztukę użytkową.',
  hero: {
    title: 'O pracowni',
    imageSrc: IMG.hero,
    imageAlt: 'ceramika prezent warszataty poznan suchy las',
    logoSrc: IMG.logo,
    logoAlt: 'pracownia ceramiczne pracownia ceramiki w poznaniu',
    intro: [
      'Pracownia Ceramiki Nero to wyjątkowe miejsce, gdzie tradycja spotyka się z nowoczesnością, a pasja do ceramiki przeradza się w sztukę użytkową.',
      'Misją Pracowni Ceramiki Nero jest promowanie sztuki ceramicznej, malarstwa i rysunku.',
      '■ Lepienie jako joga umysłu ■',
      'Podczas warsztatów dbamy o komfort uczestników, chcemy żeby poczuli się jak w swoim drugim domu wypełnionym miłością i pasją, gdzie każdy jest mile widziany.',
      'Dołącz do naszej społeczności miłośników sztuki i rzemiosła.',
      'Pozwól się zainspirować niezwykłym światem ceramiki, rysunku i malarstwa  w Pracowni ceramiki Nero.',
      'W naszej ofercie znajdziesz unikalne ceramiczne talerze i miseczki, ręcznie wykonane z miłością i dbałością o detale.',
      'Szeroki wybór akcesoriów do prezentacji potraw, które dodadzą elegancji Twoim kulinarnej kompozycjom.',
      'Jesteśmy Partnerem Sucholeskiej Karty Mieszkańca',
    ],
  },
  midCopy: {
    workshopsHeading: 'Warsztaty i Kursy',
    workshopsBody:
      'Pracownia Ceramiki Nero to także miejsce edukacji i inspiracji. Regularnie organizujemy warsztaty i kursy ceramiki, rysunku i malarstwa dla różnych grup wiekowych i poziomów zaawansowania. Pod okiem doświadczonych instruktorów uczestnicy mogą poznać tajniki pracy z gliną, od podstawowych technik formowania po zaawansowane metody zdobienia, metody malowania farbami i szkicowania ołówkiem.   Nasze warsztaty to świetna okazja do rozwijania kreatywności i spędzenia czasu w miłej atmosferze.',
    contactHeading: 'Kontakt',
    contactBody:
      'Zapraszamy do odwiedzenia naszej pracowni w sercu miasta oraz do śledzenia nas na mediach społecznościowych na Instagramie i Facebooku ceramika_nero. Chętnie odpowiemy na wszelkie pytania. Jeśli masz pomysł na indywidualne zamówienie, jesteśmy otwarci na współpracę!',
    badgeSrc: IMG.badge,
    badgeAlt:
      'pracownia ceramiki suchy las prezent złotniki piątkowo ceramiki glina',
  },
  blocks: [
    {
      id: 'stale-zajecia',
      title:
        'Cały rok można dołączyć do naszych stałych zajęć dla dzieci:  rok szkolny 2025/26',
      subtitle: 'Kurs rysunku, malarstwa i ceramiki dla dzieci 6–10 lat',
      paragraphs: [
        'Zapraszamy młodych artystów na warsztaty kreatywne, podczas których połączymy rysunek, malarstwo i lepienie z gliny w jedyną w swoim rodzaju przygodę ze sztuką!',
        '🖌️ Terminy zajęć:',
        'Poniedziałek 16:00',
        'Wtorek 17:15',
        'Czwartek 17:15',
        'To kurs, który rozwija kreatywność, będziemy kręcić na kole, tworzyć kubki, rzeźby i wiele innych.',
      ],
      bullets: [
        'Poznawać różnorodne techniki rysunku i malarstwa – ołówek, kredki, akwarele, farby akrylowe',
        'Tworzyć proste formy z gliny, rozwijając wyobraźnię i zdolności manualne',
        'NOWOŚĆ! Sensoceramika 6-10 lat to zajęcia z ceramiki i innych mas dla najmłodszych',
        'Kurs rysunek architektura dla dzieci 11+',
        '2 poziomy zajęć z ceramiki dla dzieci 11+',
      ],
      imageSrc: IMG.kidsCourse,
      imageAlt: 'Kurs rysunku, malarstwa i ceramiki dla dzieci',
      imageFirst: false,
      ctaLabel: 'Zobacz pakiety',
      ctaHref: '/dla-dzieci',
      tinted: true,
    },
    {
      id: 'warsztaty-dzieci',
      title: 'Warsztaty dla dzieci',
      bullets: [
        'Czy Twoje dziecko jest zainteresowane sztuką? Może to będzie jego nowa pasja?',
        'Chciałbyś je zapisać na kurs, który rozwija kreatywność i umiejętności manualne?',
        'Zapraszamy serdecznie na warsztaty  przeznaczone dla młodych artystów',
        'Techniki rysunku i malarstwa: ołówek, kredki, akwarele, farby akrylowe',
        'Lepienie z gliny, tworzenie prostych form',
        'Tworzenie prac inspirowanych naturą, bajkami i światem wyobraźni',
        'Ćwiczenia koordynacyjne, rozwijające koordynację ręka-oko i precyzję ruchów',
        'Zabawy plastyczne, które rozweselą i zainspirują każde dziecko',
      ],
      imageSrc: IMG.kidsWorkshops,
      imageAlt: 'Warsztaty dla dzieci w pracowni',
      imageFirst: true,
      ctaLabel: 'Zobacz pakiety',
      ctaHref: '/dla-dzieci',
      tinted: false,
    },
    {
      id: 'warsztaty-dorosli',
      title: 'Warsztaty dla dorosłych',
      bullets: [
        'warsztaty odbywają się w poniedziałki o 18.30 Ceramika dla dorosłych w stylu slow',
        'Skupiamy się na jakości, spokoju i pełnym zanurzeniu w procesie tworzenia',
        'Każde zajęcia to czas na relaks i twórcze wyzwania.',
        'Warsztaty prowadzone są przez doświadczonych ceramików, którzy z pasją dzielą się swoją wiedzą i umiejętnościami.',
        'Zapewniamy wszelkie niezbędne materiały wysokiej jakości',
        'Nie są to zajęcia stałe, można dołączyć w każdym momencie',
        'oferujemy zajęcia poranne dla dorosłych: Poranki z ceramiką',
      ],
      imageSrc: IMG.adults,
      imageAlt: 'ceramikadladoroslych.jpg',
      imageFirst: false,
      ctaLabel: 'Więcej szczegółów...',
      ctaHref: '/dla-doroslych',
      tinted: true,
    },
    {
      id: 'panienskie',
      title: 'Wieczory panieńskie',
      bullets: [
        'każdy ulepi swoje przedmioty z gliny z moją pomocą',
        'zapewniam włoskie przystawki',
        'lampka wina',
        'włoska muzyka',
        'cudowny, klimatyczny lokal',
        'w różnych pakietach oferujemy zarówno profesjonalną sesję zdjęciową jak i naukę kręcenia kołem garncarskim',
        'dostosujemy pracownię tematycznie do każdej przyszłej Panny Młodej,',
      ],
      paragraphs: ['Napisz do nas i poproś o ofertę: nerogosia@gmail.com'],
      imageSrc: IMG.bridal,
      imageAlt: '3a.jpg',
      imageFirst: true,
      ctaLabel: 'Zobacz pakiety',
      ctaHref: '/panienskie',
      tinted: false,
    },
    {
      id: 'glina-do-wina',
      title: 'Glina do wina',
      bullets: [
        'Twórcze warsztaty ceramiczne= jedna z ofert dla osób dorosłych co drugi piątek miesiąca cały rok o 19.00',
        'Stworzysz unikalne talerze, kubki, zestawy do sushi, doniczki i inne ceramiczne dzieła',
        'Degustacja wina',
        'Włoskie przystawki',
        'Włoska muzyka',
        'Profesjonalne prowadzenie',
        'Zapewnione wszystkie materiały',
        'Pomożemy wam stworzyć piękne ozdoby dla was i na prezenty dla najbliższych.',
      ],
      imageSrc: IMG.wine,
      imageAlt: 'ceramika glina do wina.jpg',
      imageFirst: false,
      ctaLabel: 'Więcej szczegółów...',
      ctaHref: '/glinadowina',
      tinted: true,
    },
    {
      id: 'firmy',
      title: 'Imprezy dla firm',
      bullets: [
        'każdy ulepi swoje przedmioty z gliny z moją pomocą lub poszkliwi zakupione w Pracowni oryginalne produkty',
        'imprezy integracyjne, tematyczne',
        'warsztaty na terenie Naszej Pracowni do 12 osób',
        'warsztaty w firmach i na piknikach w grupach do 20 do 100 osób',
        'Zapewniam wszystkie materiały i narzędzia',
        'To trwała pamiątka na całe życie',
        'Prace wypalone w profesjonalnym piecu ceramicznym będą gotowe do odbioru w ciągu 2 tygodni po lepieniu lub 1 tydzień po szkliwieniu',
      ],
      imageSrc: IMG.firms,
      imageAlt: 'Casual Meeting_edited.jpg',
      imageFirst: true,
      ctaLabel: 'Więcej szczegółów...',
      ctaHref: '/grupy-i-firmy',
      tinted: false,
    },
    {
      id: 'urodziny',
      title: 'Urodziny',
      bullets: [
        'każdy ulepi swoje przedmioty z gliny z moją pomocą',
        'urodziny tematyczne dla dzieci i dorosłych',
        'włoska muzyka',
        'cudowny, klimatyczny lokal',
      ],
      imageSrc: IMG.birthday,
      imageAlt: 'Urodziny w pracowni',
      imageFirst: false,
      ctaLabel: 'Więcej szczegółów...',
      ctaHref: '/urodziny',
      tinted: true,
    },
    {
      id: 'glina-i-rodzina',
      title: 'GLINA I RODZINA',
      bullets: [
        '2 soboty miesiąca o 15.00',
        'warsztaty rodzinne dla dzieci i rodziców',
        'od 6 roku życia- dzieci mogą przyjść z rodzicami lub same',
        'cudowny, klimatyczny lokal',
      ],
      imageSrc: IMG.family,
      imageAlt: 'GLINA I RODZINA WARSZTATY RODZINNE',
      imageFirst: true,
      ctaLabel: 'Więcej szczegółów...',
      ctaHref: '/',
      tinted: false,
    },
    {
      id: 'urodziny-malowanie',
      title: 'URODZINY Z MALOWANIEM',
      bullets: [
        'WARSZTATY MALOWANIA',
        'podczas urodzin każdy stworzy swój obraz',
        '6 6 do 100 lat',
        'cudowny, klimatyczny lokal, urodzinki od 5 do 20 osób',
      ],
      imageSrc: IMG.paintBday,
      imageAlt: 'URODZINY Z MALOWANIEM',
      imageFirst: false,
      ctaLabel: 'Napisz do nas',
      ctaHref:
        'mailto:nerogosia@gmail.com?subject=urodziny%20z%20malowaniem%20',
      tinted: true,
    },
    {
      id: 'szkoly',
      title: 'WARSZTATY CERAMICZNE DLA SZKÓŁ',
      bullets: [
        'przyjdź do naszej klimatycznej pracowni z klasą lub przyjedziemy do ciebie',
        'poznaj naszą ofertę',
        'napisz maila do : nerogosia@gmail.com i poproś o ofertę dla swojej szkoły: napisz ilu jest uczniów i ile klas, gdzie jest twoja szkoła, czy wolisz przyjechać do nas czy mamy was odwiedzić z naszą ceramiką.',
      ],
      imageSrc: IMG.schools,
      imageAlt: 'Warsztaty ceramiczne dla szkół',
      imageFirst: true,
      ctaLabel: 'Więcej szczegółów...',
      ctaHref: 'mailto:nerogosia@gmail.com',
      tinted: false,
    },
  ] satisfies SplitBlock[],
};
